[theme]
base = "dark"
primaryColor = "#A38560"
backgroundColor = "#03110D"
secondaryBackgroundColor = "#16302B"
textColor = "#E0E0E0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
